# Generated by Django 5.1 on 2025-05-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Yetkazib berildi deb belgilash'),
        ),
    ]
