# Generated by Django 5.1 on 2025-05-26 06:05

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['slug'], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Sotuvchi', 'verbose_name_plural': 'Sotuvchilar'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('OP', 'Operative'), ('EX', 'Executive'), ('AD', 'Admin')], max_length=12, null=True, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('INA', 'Inactive'), ('A', 'Active'), ('OL', 'On leave')], default='INA', max_length=12, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telefon raqam'),
        ),
    ]
