# Generated by Django 5.1 on 2025-05-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(editable=False, verbose_name='Grand Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_per_item',
            field=models.FloatField(verbose_name='Price Per Item'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(editable=False, verbose_name='Total Amount'),
        ),
    ]
