# Generated by Django 5.1 on 2025-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Sana (masalan, 2024/11/22)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(editable=False, verbose_name='Umumiy jami'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_per_item',
            field=models.FloatField(verbose_name='Tovar boshiga narx'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping',
            field=models.FloatField(verbose_name='Yetkazib berish va yuklash'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(editable=False, verbose_name='Umumiy hisob'),
        ),
    ]
